server:
  port: 80

spring:
  profiles:
    active: deploy

---
spring:
  profiles: devel

  #### jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  #### datasource
  datasource:
    url: jdbc:h2:tcp://localhost/~/develop/h2/commerce
    #    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #### h2
  h2:
    console:
      enabled: true
      path: /h2-console

  #### cache (redis)
  cache:
    cache-names: red
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600000
    type: redis

---
spring:
  profiles: deploy

  #### jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  #### datasource
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100

  #### h2
  h2:
    console:
      enabled: true
      path: /h2-console

  #### cache (redis)
  cache:
    cache-names: red
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600000
    type: redis
