server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/develop/h2/commerce
    driver-class-name: org.h2.Driver
    username: sa
    password:

