server:
  port: 80

spring:
  #### jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  #### datasource
  datasource:
    url: jdbc:h2:tcp://localhost/~/develop/h2/commerce
#    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #### h2
  h2:
    console:
      enabled: true
      path: /h2-console

  #### cache (redis)
  cache:
    cache-names: red
    redis:
      host: localhost
      port: 6379
      time-to-live: 3600000
    type: redis
